include:
  - project: dwp/engineering/pipeline-solutions/gitlab/functions
    ref: 6.1.9
    file: functions/node-mr.gitlab-ci.yml

variables:
  FUNCTIONS_SONARQUBE_ENABLED: "false"
  NODE_IMAGE: node:22.20.0-alpine@sha256:dbcedd8aeab47fbc0f4dd4bffa55b7c3c729a707875968d467aaaea42d6225af
  GITLAB_AUTH_TOKEN: '${CI_JOB_TOKEN}'
